CREATE TABLE PART(
    PNO NUMBER,
    PNAME VARCHAR(10),
    COLOUR VARCHAR(10),
    PRIMARY KEY(PNO)
);

CREATE TABLE SUPPLIER(
    SNO VARCHAR(10),
    SNAME VARCHAR(10),
    ADDRESS VARCHAR(10),
    PRIMARY KEY(SNO)
);

CREATE TABLE SUPPLY(
    PNO NUMBER,
    SNO VARCHAR(10),
    QUANTITY NUMBER,
    FOREIGN KEY(PNO) REFERENCES PART(PNO) ON DELETE CASCADE,
    FOREIGN KEY(SNO) REFERENCES SUPPLIER(SNO) ON DELETE CASCADE,
    PRIMARY KEY(PNO,SNO)
);

INSERT INTO PART VALUES(&PNO,'&PNAME','&COLOUR');

INSERT INTO SUPPLIER VALUES('&SNO','&SNAME','&ADDRESS');

INSERT INTO SUPPLY VALUES(&PNO,'&SNO',&QUANTITY);

SELECT PNO
FROM SUPPLY
WHERE SNO IN (
    SELECT SNO
    FROM SUPPLIER
    WHERE SNAME = 'RAM'
);

SELECT SNAME
FROM SUPPLIER
WHERE SNO IN (
    SELECT SNO
    FROM SUPPLY
    WHERE PNO IN (
            SELECT PNO
            FROM PART
            WHERE PNAME = 'BOLTS'
    )
);

DELETE FROM PART
WHERE COLOUR = 'GREEN';
