CREATE TABLE BOOK(  
    ISBN VARCHAR(10),
    TITLE VARCHAR(10),
    AUTHOR VARCHAR(10),
    PUBLISHER VARCHAR(10),
    PRIMARY KEY(ISBN));

CREATE TABLE STUDENT(
USN VARCHAR(10),
NAME VARCHAR(10),
SEM NUMBER,
DEPTNO NUMBER,
PRIMARY KEY(USN)
);

CREATE TABLE BORROW(
    ISBN VARCHAR(10),
    USN VARCHAR(10),
    DAT VARCHAR(10),
    FOREIGN KEY(ISBN) REFERENCES BOOK(ISBN) ON DELETE CASCADE,
    FOREIGN KEY(USN) REFERENCES STUDENT(USN) ON DELETE CASCADE,
    PRIMARY KEY(ISBN,USN)
);

SELECT NAME
FROM STUDENT
WHERE USN IN (
    SELECT USN
    FROM BORROW
    WHERE ISBN = '123'
);

SELECT NAME
FROM STUDENT
WHERE USN IN (
    SELECT USN
    FROM BORROW
    WHERE ISBN = (
        SELECT ISBN
        FROM BOOK
        WHERE TITLE = 'DATABASE'
    )
);

SELECT USN,COUNT(*)
FROM BORROW
GROUP BY USN;
